#!/usr/bin/python3
from cryptography.hazmat.primitives.asymmetric import x25519
from cryptography.hazmat.primitives import serialization
from base64 import b64encode
import datetime
import segno
import requests
import argparse
import json
import sys
import os

VERSION = 1.0

BASE_URL = "https://api.cloudflareclient.com/v0a1922"
HEADERS = {
    "User-Agent": "okhttp/3.12.1",
    "Cf-Client-Version": "a-6.3-1922",
}


def register():
    private_key_object = x25519.X25519PrivateKey.generate()
    private_key = b64encode(
        private_key_object.private_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PrivateFormat.Raw,
            encryption_algorithm=serialization.NoEncryption(),
        )
    ).decode("utf-8")
    public_key = b64encode(
        private_key_object.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw,
        )
    ).decode("utf-8")

    res_json = {
        "fcm_token": "",
        "install_id": "",
        "key": public_key,
        "locale": "en_US",
        "model": "PC",
        "tos": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "type": "Android",
    }

    with requests.Session() as session:
        session.headers.update(HEADERS)
        config_res = session.post(
            f"{BASE_URL}/reg",
            json=res_json,
        )
        config_res.raise_for_status()
        config_res_json = config_res.json()
        aid, token = config_res_json["id"], config_res_json["token"]
        session.headers.update(
            {
                "Authorization": f"Bearer {token}",
            }
        )
        verify_res = session.get(
            f"{BASE_URL}/reg/{aid}/account/devices",
        )
        verify_res.raise_for_status()
        verify_res_json = verify_res.json()
        assert verify_res_json[0]["id"] == aid
        assert verify_res_json[0]["active"] == True

    config_res_json["private_key"] = private_key
    return config_res_json


def generate_config(reg, include_dns=False):
    config, comments = [], []
    config.append("[Interface]")
    config.append(f'PrivateKey = {reg["private_key"]}')
    config.append(f'Address = {reg["config"]["interface"]["addresses"]["v4"]}/32')
    config.append(f'Address = {reg["config"]["interface"]["addresses"]["v6"]}/128')
    if include_dns:
        config.append(
            f"DNS = 1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001"
        )
    config.append("MTU = 1280")
    config.append("")
    config.append("[Peer]")
    config.append(f'PublicKey = {reg["config"]["peers"][0]["public_key"]}')
    config.append("AllowedIPs = 0.0.0.0/0")
    config.append("AllowedIPs = ::/0")
    config.append(f'Endpoint = {reg["config"]["peers"][0]["endpoint"]["host"]}')
    config.append("")

    comments.append("# TTL: " + reg["account"]["ttl"])
    comments.append("# Generated by https://github.com/rafiibrahim8/ir8tools")
    comments.append("# " + json.dumps(reg))
    comments.append("")
    return "\n".join(config), "\n".join(comments)


def get_and_save_config(output, include_dns=False):
    reg = register()
    config, comments = generate_config(reg, include_dns)

    ttl = datetime.datetime.fromisoformat(reg["account"]["ttl"])
    print(f'Expires on {ttl.strftime("%B %d, %Y at %H:%M:%S UTC")}', file=sys.stderr)
    print(file=sys.stderr)

    if output["type"] == "qr":
        compact_config = config.replace("\n\n", "\n").replace(" ", "")
        segno.make(compact_config).terminal(border=1, compact=True)
    elif not not output["path"].strip():
        with open(output["path"], "w") as f:
            f.write(config + comments)
        print(f"Configuration saved to {output['path'].strip()}", file=sys.stderr)
    else:
        print(config)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a WireGuard configuration file for Cloudflare WARP",
        add_help=False,
    )
    parser.add_argument(
        "-d",
        "--dns",
        action="store_true",
        help="Include DNS servers in the configuration",
    )
    output_group = parser.add_mutually_exclusive_group()
    output_group.add_argument(
        "-o",
        "--output",
        default="warp.conf",
        help="Output file path, pass `-` to print too stdout",
    )
    output_group.add_argument(
        "-q", "--qr", action="store_true", help="Print QR config to stdout"
    )
    parser.add_argument(
        "-v",
        "--version",
        help="Prints version information.",
        action="version",
        version="v" + str(VERSION),
    )
    parser.add_argument(
        "-h", "--help", help="Show this help message and exit.", action="help"
    )
    args = parser.parse_args()
    output = (
        {"type": "qr"}
        if args.qr
        else {
            "type": "file",
            "path": "" if args.output == "-" else os.path.expanduser(args.output),
        }
    )
    get_and_save_config(output, include_dns=args.dns)


if __name__ == "__main__":
    main()
